DROP TABLE IF EXISTS users_image CASCADE;

CREATE TABLE IF NOT EXISTS users_image(
                                          user_image_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          user_id INTEGER NOT NULL,
                                          user_image_path VARCHAR(255)
    );

INSERT INTO users_image (user_id, user_image_path)
VALUES
    (2, 'user_2_picForShareStorageAvaVlada.jpeg'),
    (3, 'user_3_picForShareStorageAvaTolya.avif'),
    (1, 'user_1_cropped-p231106173215.jpg'),
    (4, 'user_4_picForShareStorageIlyas.webp');


DROP TABLE IF EXISTS items_image CASCADE;

CREATE TABLE IF NOT EXISTS items_image(
                                          item_image_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          item_id INTEGER NOT NULL,
                                          item_image_path VARCHAR(255)
    );

INSERT INTO items_image (item_id, item_image_path)
VALUES
    (2, 'item_2_picForShareStorage2.jpeg'),
    (3, 'item_3_picForShareStorageVlad.jpeg'),
    (4, 'item_4_picForShareStorage4.jpeg'),
    (1, 'item_1_picForShareStorage1.jpeg'),
    (6, 'item_6_picForShareStorageIOS.png');

CREATE TABLE IF NOT EXISTS groups_image(
                                           group_image_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           group_id INTEGER NOT NULL,
                                           group_image_path VARCHAR(255)
    );

INSERT INTO groups_image (group_id, group_image_path)
VALUES
    (1, 'group_1_picForShareStorageSchool21Group.jpeg'),
    (2, 'group_2_picForShareStorageOzernaya.jpeg');