DROP TABLE IF EXISTS rental_items CASCADE;

CREATE TABLE IF NOT EXISTS rental_items(
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER NOT NULL,
    owner_name VARCHAR(100) NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(250) NOT NULL,
    status INTEGER NOT NULL,
    group_id INTEGER,
    group_name VARCHAR(100)
    );

INSERT INTO rental_items (owner_id, owner_name, title, description, status)
VALUES
    (1, 'SANAN', 'Корм для птиц', 'Однажды я нашел на остановке корм для птиц. Он пролежал у меня дома месяца 3, после чего его пришлось выкинуть, потому что не смог найти кому из моих знакомых он нужен', 0);

INSERT INTO rental_items(owner_id, owner_name, title, description, status, group_id, group_name)
VALUES
    (1, 'SANAN', 'Табуретки ikea', 'Еще у меня на балконе лежат 2 ненужные табуретки(на самом деле не только они)', 0, 2, 'Озерная 9');

INSERT INTO rental_items (owner_id, owner_name, title, description, status)
VALUES
    (2, 'gazeta@gmail.com', 'Газета', 'Взял газету в метро у бабушки. Могу отдать', 0),
    (3, 'yshkin@yandex.ru', 'Усилитель слуха', 'Прибор рабочий, сам опробовал, 10 из 10', 0);

INSERT INTO rental_items(owner_id, owner_name, title, description, status, group_id, group_name)
VALUES
    (3, 'yshkin@yandex.ru', 'Помощь с ДЖАВОЙ', 'Могу помочь с ДЖАВОЙ. Я СЕКЬЮРИТИ МАСТЕР', 0, 1, 'Школьники21'),
    (4, 'izhanaev@mail.ru', 'Любое мобильное приложение на iOS', 'Разработка любого iOS приложения, стоимость 100$ / час, оплата наличными/переводом', 0, 1, 'Школьники21');


DROP TABLE IF EXISTS rent_contracts CASCADE;

CREATE TABLE IF NOT EXISTS rent_contracts(
    contract_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER REFERENCES rental_items(item_id) NOT NULL,
    borrower_id INTEGER NOT NULL,
    borrower_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    reserved_to TIMESTAMP,
    reserved_from TIMESTAMP,
    comment VARCHAR(250),
    status INTEGER NOT NULL
    );

INSERT INTO rent_contracts (item_id, borrower_id, borrower_name, created_at, updated_at, reserved_to, reserved_from, comment, status)
VALUES
    (3, 1, 'SANAN', '2024-02-06 20:40:39.37881', NULL, '2024-02-07 23:59:00', '2024-02-06 23:59:00', 'ВЛАААААД, дай ПЖ газету до заввтра почитать', 205),
    (3, 3, 'yshkin@yandex.ru', '2024-02-07 17:05:18.159392', NULL, '2024-02-08 23:59:00', '2024-02-07 23:59:00', 'Никому не верь, отдай газету мне!', 205),
    (6, 1, 'SANAN', '2024-02-15 16:30:51.642434', NULL, NULL, NULL, 'Привет!!! Я ОВНЕР группы "Школьники 21". Мне нужно приложение для этого сервиса на АЙОС. НО у меня нет деняк, предлагаю БЕСЦЕННЫЙ опыт участия в СТАРТАПЕ такого уровня как этот', 205);
