#!/bin/bash

# Создание базы данных "authorized_users"
psql -U sanan -c "CREATE DATABASE authorized_users;"

# Выполнение SQL-скрипта
psql -U sanan -d authorized_users -c "
    DROP TABLE IF EXISTS users_roles CASCADE;
    DROP TABLE IF EXISTS users CASCADE;
    DROP TABLE IF EXISTS roles CASCADE;

    CREATE TABLE IF NOT EXISTS roles(
        role_id serial,
        role_name varchar(20) UNIQUE NOT NULL,
        PRIMARY KEY (role_id)
    );

    CREATE TABLE IF NOT EXISTS users(
        user_id serial,
        first_name varchar(20),
        last_name varchar(20),
        email varchar(20) UNIQUE not null,
        password varchar(100) not null,
        PRIMARY KEY (user_id)
    );

    CREATE TABLE IF NOT EXISTS users_roles (
        user_id integer NOT NULL,
        role_id integer NOT NULL,
        PRIMARY KEY (user_id, role_id),
        CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
        CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES roles (role_id) ON UPDATE CASCADE
    );

    INSERT INTO roles(role_id, role_name)
    VALUES (1, 'ROLE_ADMIN'), (2, 'ROLE_USER');
"

# Создание базы данных "items_service_db"
psql -U sanan -c "CREATE DATABASE users_service_db;"


# Выполнение SQL-скрипта
psql -U sanan -d users_service_db -c "
    DROP TABLE IF EXISTS users CASCADE;

    CREATE TABLE IF NOT EXISTS users(
    user_id SERIAL PRIMARY KEY,
    login VARCHAR(50) NOT NULL,
    email VARCHAR(255) UNIQUE,
    phone_number VARCHAR(11),
    introduce VARCHAR(255),
    created_at TIMESTAMP
    );

    INSERT INTO users(login, phone_number, introduce, email) VALUES
    ('Aboba', '81234567890', 'ABOBA TEST USER ','aboba@mail.com'),
    ('Tom', '80987654321', 'TOM TEST USER', 'tom@mail.com'),
    ('Bob', '89990001234', 'BOB TEST USER', 'bob@mail.com'),
    ('Katy', '80001112345', 'KATY TEST USER', 'katy@mail.com');
"


# Создание базы данных "items_service_db"
psql -U sanan -c "CREATE DATABASE items_service_db;"

# Выполнение SQL-скрипта
psql -U sanan -d items_service_db -c "
    DROP TABLE IF EXISTS rental_items CASCADE;

    CREATE TABLE IF NOT EXISTS rental_items(
        item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_id INTEGER NOT NULL,
        owner_name VARCHAR(100) NOT NULL,
        title VARCHAR(100) NOT NULL,
        description VARCHAR(250) NOT NULL,
        status INTEGER NOT NULL,
        cost_hour INTEGER,
        cost_day INTEGER
        );

    INSERT INTO rental_items(owner_id, owner_name, title, description, status, cost_hour, cost_day) VALUES(1, 'ABOBA', 'CAR', 'CAR BY ABOBA', 0, 500, 6000);
    INSERT INTO rental_items(owner_id, owner_name, title, description, status, cost_hour) VALUES(2, 'TOM', 'PERSONAL LESSONS', 'PERSONAL DANCE LESSON', 0, 800);
    INSERT INTO rental_items(owner_id, owner_name, title, description, status, cost_day) VALUES(1, 'ABOBA','DOM', 'DOM BY ABOBA', 1, 3000);


    DROP TABLE IF EXISTS rent_contracts CASCADE;

    CREATE TABLE IF NOT EXISTS rent_contracts(
        contract_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        item_id INTEGER REFERENCES rental_items(item_id) NOT NULL,
        borrower_id INTEGER NOT NULL,
        created_at TIMESTAMP NOT NULL,
        updated_at TIMESTAMP,
        reserved_to TIMESTAMP,
        reserved_from TIMESTAMP,
        comment VARCHAR(250),
        status INTEGER NOT NULL
        );

    INSERT INTO rent_contracts(item_id, borrower_id, created_at, reserved_from, reserved_to, status) VALUES (3, 4, '2024-01-18 12:34:56', '2024-01-20 00:00:00', '2025-01-20 00:00:00', 201);
"
